import Foundation

/// Word lists used for colouring and completion. Kept close to what SSMS highlights.
public enum TSQLKeywords {

    public static let reserved: Set<String> = [
        "ADD", "ALL", "ALTER", "AND", "ANY", "AS", "ASC", "AUTHORIZATION", "BACKUP", "BEGIN",
        "BETWEEN", "BREAK", "BROWSE", "BULK", "BY", "CASCADE", "CASE", "CHECK", "CHECKPOINT",
        "CLOSE", "CLUSTERED", "COALESCE", "COLLATE", "COLUMN", "COMMIT", "COMPUTE", "CONSTRAINT",
        "CONTAINS", "CONTAINSTABLE", "CONTINUE", "CONVERT", "CREATE", "CROSS", "CURRENT",
        "CURRENT_DATE", "CURRENT_TIME", "CURRENT_TIMESTAMP", "CURRENT_USER", "CURSOR",
        "DATABASE", "DBCC", "DEALLOCATE", "DECLARE", "DEFAULT", "DELETE", "DENY", "DESC",
        "DISK", "DISTINCT", "DISTRIBUTED", "DOUBLE", "DROP", "DUMP", "ELSE", "END", "ERRLVL",
        "ESCAPE", "EXCEPT", "EXEC", "EXECUTE", "EXISTS", "EXIT", "EXTERNAL", "FETCH", "FILE",
        "FILLFACTOR", "FOR", "FOREIGN", "FREETEXT", "FREETEXTTABLE", "FROM", "FULL", "FUNCTION",
        "GOTO", "GRANT", "GROUP", "HAVING", "HOLDLOCK", "IDENTITY", "IDENTITYCOL",
        "IDENTITY_INSERT", "IF", "IN", "INDEX", "INNER", "INSERT", "INTERSECT", "INTO", "IS",
        "JOIN", "KEY", "KILL", "LEFT", "LIKE", "LINENO", "LOAD", "MERGE", "NATIONAL",
        "NOCHECK", "NONCLUSTERED", "NOT", "NULL", "NULLIF", "OF", "OFF", "OFFSETS", "ON",
        "OPEN", "OPENDATASOURCE", "OPENQUERY", "OPENROWSET", "OPENXML", "OPTION", "OR",
        "ORDER", "OUTER", "OVER", "PERCENT", "PIVOT", "PLAN", "PRECISION", "PRIMARY", "PRINT",
        "PROC", "PROCEDURE", "PUBLIC", "RAISERROR", "READ", "READTEXT", "RECONFIGURE",
        "REFERENCES", "REPLICATION", "RESTORE", "RESTRICT", "RETURN", "REVERT", "REVOKE",
        "RIGHT", "ROLLBACK", "ROWCOUNT", "ROWGUIDCOL", "RULE", "SAVE", "SCHEMA",
        "SECURITYAUDIT", "SELECT", "SEMANTICKEYPHRASETABLE", "SEMANTICSIMILARITYDETAILSTABLE",
        "SEMANTICSIMILARITYTABLE", "SESSION_USER", "SET", "SETUSER", "SHUTDOWN", "SOME",
        "STATISTICS", "SYSTEM_USER", "TABLE", "TABLESAMPLE", "TEXTSIZE", "THEN", "TO", "TOP",
        "TRAN", "TRANSACTION", "TRIGGER", "TRUNCATE", "TRY_CONVERT", "TSEQUAL", "UNION",
        "UNIQUE", "UNPIVOT", "UPDATE", "UPDATETEXT", "USE", "USER", "VALUES", "VARYING",
        "VIEW", "WAITFOR", "WHEN", "WHERE", "WHILE", "WITH", "WITHIN", "WRITETEXT",
        // control-of-flow and common modifiers SSMS colours too
        "TRY", "CATCH", "THROW", "APPLY", "OUTPUT", "OUT", "READONLY", "RETURNS", "AFTER",
        "INSTEAD", "NOLOCK", "ROWLOCK", "TABLOCK", "TABLOCKX", "UPDLOCK", "XLOCK", "PAGLOCK",
        "MAXDOP", "RECOMPILE", "OPTIMIZE", "FAST", "FORCESEEK", "IGNORE_DUP_KEY", "INCLUDE",
        "PARTITION", "RANGE", "ROWS", "PRECEDING", "FOLLOWING", "UNBOUNDED", "CURRENT_ROW",
        "GO", "OFFSET", "NEXT", "ONLY", "FIRST", "LAST", "NULLS", "SEQUENCE", "CACHE",
        "IDENTITY_VALUE", "SPARSE", "FILESTREAM", "FILETABLE", "MASKED", "ENCRYPTED",
        "PERIOD", "SYSTEM_TIME", "SYSTEM_VERSIONING", "HISTORY_TABLE", "GENERATED", "ALWAYS",
        "HIDDEN", "CONCAT", "DATA_COMPRESSION", "ONLINE", "RESUMABLE", "SORT_IN_TEMPDB",
        "SCHEMABINDING", "VIEW_METADATA", "ENCRYPTION", "CALLER", "SELF", "OWNER", "LOGIN",
        "PASSWORD", "MUST_CHANGE", "CHECK_POLICY", "CHECK_EXPIRATION", "DEFAULT_DATABASE",
        "DEFAULT_LANGUAGE", "SID", "ROLE", "MEMBER", "ADMINISTER", "CONNECT", "IMPERSONATE",
        "CONTROL", "TAKE", "OWNERSHIP", "ALTERANY", "DATABASES", "DEFINITION"
    ]

    public static let dataTypes: Set<String> = [
        "BIGINT", "BINARY", "BIT", "CHAR", "CHARACTER", "DATE", "DATETIME", "DATETIME2",
        "DATETIMEOFFSET", "DEC", "DECIMAL", "FLOAT", "GEOGRAPHY", "GEOMETRY", "HIERARCHYID",
        "IMAGE", "INT", "INTEGER", "MONEY", "NCHAR", "NTEXT", "NUMERIC", "NVARCHAR", "REAL",
        "ROWVERSION", "SMALLDATETIME", "SMALLINT", "SMALLMONEY", "SQL_VARIANT", "SYSNAME",
        "TEXT", "TIME", "TIMESTAMP", "TINYINT", "UNIQUEIDENTIFIER", "VARBINARY", "VARCHAR",
        "XML", "MAX", "CURSOR", "TABLE"
    ]

    public static let functions: Set<String> = [
        "ABS", "ACOS", "ASIN", "ATAN", "ATN2", "AVG", "CEILING", "CHARINDEX", "CHECKSUM",
        "CHOOSE", "COALESCE", "CONCAT", "CONCAT_WS", "COS", "COT", "COUNT", "COUNT_BIG",
        "CUME_DIST", "CURRENT_TIMESTAMP", "DATALENGTH", "DATEADD", "DATEDIFF", "DATEFROMPARTS",
        "DATENAME", "DATEPART", "DAY", "DEGREES", "DENSE_RANK", "DIFFERENCE", "EOMONTH",
        "ERROR_LINE", "ERROR_MESSAGE", "ERROR_NUMBER", "ERROR_PROCEDURE", "ERROR_SEVERITY",
        "ERROR_STATE", "EXP", "FIRST_VALUE", "FLOOR", "FORMAT", "GETDATE", "GETUTCDATE",
        "GROUPING", "GROUPING_ID", "HASHBYTES", "IIF", "ISDATE", "ISJSON", "ISNULL",
        "ISNUMERIC", "JSON_MODIFY", "JSON_QUERY", "JSON_VALUE", "LAG", "LAST_VALUE", "LEAD",
        "LEFT", "LEN", "LOG", "LOG10", "LOWER", "LTRIM", "MAX", "MIN", "MONTH", "NCHAR",
        "NEWID", "NEWSEQUENTIALID", "NTILE", "OBJECT_ID", "OBJECT_NAME", "OBJECT_SCHEMA_NAME",
        "OPENJSON", "PARSE", "PATINDEX", "PERCENTILE_CONT", "PERCENTILE_DISC", "PERCENT_RANK",
        "PI", "POWER", "QUOTENAME", "RADIANS", "RAND", "RANK", "REPLACE", "REPLICATE",
        "REVERSE", "RIGHT", "ROUND", "ROW_NUMBER", "RTRIM", "SCHEMA_NAME", "SCOPE_IDENTITY",
        "SIGN", "SIN", "SOUNDEX", "SPACE", "SQL_VARIANT_PROPERTY", "SQRT", "SQUARE", "STDEV",
        "STDEVP", "STR", "STRING_AGG", "STRING_ESCAPE", "STRING_SPLIT", "STUFF", "SUBSTRING",
        "SUM", "SUSER_NAME", "SUSER_SNAME", "SWITCHOFFSET", "SYSDATETIME", "SYSDATETIMEOFFSET",
        "SYSUTCDATETIME", "TAN", "TODATETIMEOFFSET", "TRANSLATE", "TRIM", "TRY_CAST",
        "TRY_CONVERT", "TRY_PARSE", "TYPE_NAME", "UNICODE", "UPPER", "USER_NAME", "VAR",
        "VARP", "YEAR", "CAST", "@@ROWCOUNT", "@@IDENTITY", "@@ERROR", "@@VERSION",
        "@@SERVERNAME", "@@SPID", "@@TRANCOUNT"
    ]

    /// Ordered list used by the completion popup when nothing more specific matches.
    public static let allCompletionWords: [String] = {
        var words = Set<String>()
        words.formUnion(reserved)
        words.formUnion(dataTypes)
        words.formUnion(functions)
        return words.sorted()
    }()
}
